[package]
name = "dalia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
infer = "0.8.1"
walkdir = "2.3.2"
kamadak-exif = "0.5.4"
chrono = "0.4"
